export const markets = [
  "AUD,Australian Dollar",
  "CAD,Canadian Dollar",
  "CHF,Swiss Franc",
  "CNY,Chinese Yuan",
  "EUR,Euro",
  "GBP,British Pound Sterling",
  "RUB,Russian Ruble",
  "USD,United States Dollar",
];

export const symbols = {
  stocks: [
    "AAPL,Apple Inc",
    "ADBE,Adobe Inc",
    "AMD,Advanced Micro Devices, Inc",
    "AMZN,Amazon.com, Inc",
    "ASML,ASML Holding N.V",
    "AVGO,Broadcom Inc",
    "COST,Costco Wholesale Corporation",
    "CSCO,Cisco Systems, Inc",
    "GOOG,Alphabet Inc. (Class C)",
    "GOOGL Alphabet Inc. (Class A)",
    "INTC,Intel Corporation",
    "META,Meta Platforms Inc",
    "MSFT,Microsoft Corporation",
    "NFLX,Netflix Inc",
    "NVDA,NVIDIA Corporation",
    "PEP,PepsiCo Inc.",
    "PYPL,PayPal Holdings Inc",
    "QCOM,Qualcomm Incorporated",
    "TSLA,Tesla Inc",
    "TXN,Texas Instruments Incorporated",
  ],
  crypto: [
    "AAVE,Aave",
    "ADA,Cardano",
    "ATOM,Cosmos",
    "AVAX,Avalanche",
    "BNB,Binance-Coin",
    "BTC,Bitcoin",
    "BUSD,Binance-USD",
    "CAKE,PancakeSwap",
    "COMP,Compound",
    "DAI,Dai",
    "DASH,Dash",
    "DOGE,DogeCoin",
    "DOT,Polkadot",
    "ELIX,Elixir",
    "EOS,EOS",
    "ETH,Ethereum",
    "LINK,ChainLink",
    "LTC,Litecoin",
    "MATIC,Polygon",
    "NEO,NEO",
    "UNI,Uniswap",
    "UST,TerraUSD",
    "XRP,Ripple",
    "XZC,ZCoin",
  ],
};
